// examples/angular-todo/src/app/app.component.ts
/**
 * App Component
 * 
 * Root component that initializes the Mycelia system.
 */

import { Component, OnInit, OnDestroy } from '@angular/core';
import { MyceliaService } from './services/mycelia.service';
import { buildTodoSystem } from '../../todo-shared/src/system.builder.js';

@Component({
  selector: 'app-root',
  template: `
    <div *ngIf="loading" class="loading">Loading Todo system…</div>
    <div *ngIf="error" class="error">Error: {{ error.message }}</div>
    <app-todo-app *ngIf="!loading && !error"></app-todo-app>
  `,
  styles: [`
    .loading, .error {
      padding: 20px;
      text-align: center;
    }
  `]
})
export class AppComponent implements OnInit, OnDestroy {
  loading = true;
  error: Error | null = null;

  constructor(private mycelia: MyceliaService) {}

  async ngOnInit() {
    try {
      // Initialize Mycelia system
      await this.mycelia.initialize(buildTodoSystem);
      this.loading = false;
    } catch (err) {
      this.error = err as Error;
      this.loading = false;
      console.error('Failed to build system:', err);
    }
  }

  async ngOnDestroy() {
    await this.mycelia.dispose();
  }
}

// examples/svelte-todo/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { setMyceliaSystem } from '../../../src/svelte/index.js';
  import { buildTodoSystem } from '../../todo-shared/src/system.builder.js';
  import TodoApp from './components/TodoApp.svelte';

  let system;
  let loading = true;
  let error = null;

  onMount(async () => {
    try {
      system = await buildTodoSystem('svelte-todo-app');
      setMyceliaSystem(system);
      loading = false;
    } catch (err) {
      error = err;
      loading = false;
      console.error('Failed to build system:', err);
    }
  });

  onDestroy(async () => {
    if (system) {
      await system.dispose();
    }
  });
</script>

{#if loading}
  <div>Loading Todo system…</div>
{:else if error}
  <div>Error: {error.message}</div>
{:else}
  <TodoApp />
{/if}
