// examples/react-todo/src/react/components/TodoList.jsx
/**
 * TodoList Component
 * 
 * Displays a list of todos.
 */

import React from 'react';
import { TodoItem } from './TodoItem.jsx';

/**
 * @typedef {Object} Todo
 * @property {string} id - Unique identifier
 * @property {string} text - Todo text
 * @property {boolean} completed - Completion status
 * @property {number} createdAt - Timestamp
 */

export function TodoList({ items, onToggle, onRemove }) {
  if (!items.length) {
    return <p className="empty">Nothing here yet.</p>;
  }

  return (
    <ul className="todo-list">
      {items.map((todo) => (
        <TodoItem
          key={todo.id}
          todo={todo}
          onToggle={() => onToggle(todo.id)}
          onRemove={() => onRemove(todo.id)}
        />
      ))}
    </ul>
  );
}

// examples/qwik-todo/src/components/TodoList.tsx
/**
 * TodoList Component
 * 
 * Displays a list of todos.
 */

import { component$ } from '@builder.io/qwik';
import { TodoItem } from './TodoItem';
import type { Todo } from './TodoApp';

interface TodoListProps {
  items: Todo[];
  onToggle$: (id: string) => void;
  onRemove$: (id: string) => void;
}

export const TodoList = component$<TodoListProps>(({ items, onToggle$, onRemove$ }) => {
  if (!items.length) {
    return <p class="empty">Nothing here yet.</p>;
  }

  return (
    <ul class="todo-list">
      {items.map((todo) => (
        <TodoItem
          key={todo.id}
          todo={todo}
          onToggle$={() => onToggle$(todo.id)}
          onRemove$={() => onRemove$(todo.id)}
        />
      ))}
    </ul>
  );
});
